In [3]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [4]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [5]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  4.6566e-10  0.0000e+00
 4.6566e-10  2.5622e-27  1.4013e-45
 4.5473e-27  1.4013e-45 -1.7692e-28
 4.5902e-41  0.0000e+00  0.0000e+00
-1.7879e-28  4.5902e-41  2.6400e+15
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [6]:
x = torch.rand(5, 3)
print(x)


 0.9211  0.5432  0.2487
 0.1063  0.4942  0.0822
 0.2390  0.4087  0.3144
 0.7688  0.2774  0.3838
 0.7081  0.8846  0.8370
[torch.FloatTensor of size 5x3]



Get its size



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)


 1.2091  1.3672  1.0480
 0.3916  0.7656  0.4078
 0.2505  1.0624  1.1129
 1.4982  0.7121  0.8765
 1.6776  0.9116  1.5593
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [9]:
print(torch.add(x, y))


 1.2091  1.3672  1.0480
 0.3916  0.7656  0.4078
 0.2505  1.0624  1.1129
 1.4982  0.7121  0.8765
 1.6776  0.9116  1.5593
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [10]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.2091  1.3672  1.0480
 0.3916  0.7656  0.4078
 0.2505  1.0624  1.1129
 1.4982  0.7121  0.8765
 1.6776  0.9116  1.5593
[torch.FloatTensor of size 5x3]



Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)


 1.2091  1.3672  1.0480
 0.3916  0.7656  0.4078
 0.2505  1.0624  1.1129
 1.4982  0.7121  0.8765
 1.6776  0.9116  1.5593
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])


 0.5432
 0.4942
 0.4087
 0.2774
 0.8846
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [13]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [14]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [15]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [17]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y